using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class GameScreenModel
{
    [RealtimeProperty(1, true, true)]
    private string _currentTurnNumber;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class GameScreenModel : RealtimeModel {
    public string currentTurnNumber {
        get {
            return _currentTurnNumberProperty.value;
        }
        set {
            if (_currentTurnNumberProperty.value == value) return;
            _currentTurnNumberProperty.value = value;
            InvalidateReliableLength();
            FireCurrentTurnNumberDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(GameScreenModel model, T value);
    public event PropertyChangedHandler<string> currentTurnNumberDidChange;
    
    public enum PropertyID : uint {
        CurrentTurnNumber = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _currentTurnNumberProperty;
    
    #endregion
    
    public GameScreenModel() : base(null) {
        _currentTurnNumberProperty = new ReliableProperty<string>(1, _currentTurnNumber);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _currentTurnNumberProperty.UnsubscribeCallback();
    }
    
    private void FireCurrentTurnNumberDidChange(string value) {
        try {
            currentTurnNumberDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _currentTurnNumberProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _currentTurnNumberProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.CurrentTurnNumber: {
                    changed = _currentTurnNumberProperty.Read(stream, context);
                    if (changed) FireCurrentTurnNumberDidChange(currentTurnNumber);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _currentTurnNumber = currentTurnNumber;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
