using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class IdModel
{
    [RealtimeProperty(1, true, true)]
    private string _id;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class IdModel : RealtimeModel {
    public string id {
        get {
            return _idProperty.value;
        }
        set {
            if (_idProperty.value == value) return;
            _idProperty.value = value;
            InvalidateReliableLength();
            FireIdDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(IdModel model, T value);
    public event PropertyChangedHandler<string> idDidChange;
    
    public enum PropertyID : uint {
        Id = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _idProperty;
    
    #endregion
    
    public IdModel() : base(null) {
        _idProperty = new ReliableProperty<string>(1, _id);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _idProperty.UnsubscribeCallback();
    }
    
    private void FireIdDidChange(string value) {
        try {
            idDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _idProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _idProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Id: {
                    changed = _idProperty.Read(stream, context);
                    if (changed) FireIdDidChange(id);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _id = id;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
