using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class BackgroundMusicPlayModel
{
    [RealtimeProperty(1, true, true)]
    private string _playlistIds;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class BackgroundMusicPlayModel : RealtimeModel {
    public string playlistIds {
        get {
            return _playlistIdsProperty.value;
        }
        set {
            if (_playlistIdsProperty.value == value) return;
            _playlistIdsProperty.value = value;
            InvalidateReliableLength();
            FirePlaylistIdsDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(BackgroundMusicPlayModel model, T value);
    public event PropertyChangedHandler<string> playlistIdsDidChange;
    
    public enum PropertyID : uint {
        PlaylistIds = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _playlistIdsProperty;
    
    #endregion
    
    public BackgroundMusicPlayModel() : base(null) {
        _playlistIdsProperty = new ReliableProperty<string>(1, _playlistIds);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _playlistIdsProperty.UnsubscribeCallback();
    }
    
    private void FirePlaylistIdsDidChange(string value) {
        try {
            playlistIdsDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _playlistIdsProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _playlistIdsProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.PlaylistIds: {
                    changed = _playlistIdsProperty.Read(stream, context);
                    if (changed) FirePlaylistIdsDidChange(playlistIds);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _playlistIds = playlistIds;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
