using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class ChessGameControlModel
{
    [RealtimeProperty(1, true, true)]
    private int _lastPlayedSequenceId;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ChessGameControlModel : RealtimeModel {
    public int lastPlayedSequenceId {
        get {
            return _lastPlayedSequenceIdProperty.value;
        }
        set {
            if (_lastPlayedSequenceIdProperty.value == value) return;
            _lastPlayedSequenceIdProperty.value = value;
            InvalidateReliableLength();
            FireLastPlayedSequenceIdDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ChessGameControlModel model, T value);
    public event PropertyChangedHandler<int> lastPlayedSequenceIdDidChange;
    
    public enum PropertyID : uint {
        LastPlayedSequenceId = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _lastPlayedSequenceIdProperty;
    
    #endregion
    
    public ChessGameControlModel() : base(null) {
        _lastPlayedSequenceIdProperty = new ReliableProperty<int>(1, _lastPlayedSequenceId);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _lastPlayedSequenceIdProperty.UnsubscribeCallback();
    }
    
    private void FireLastPlayedSequenceIdDidChange(int value) {
        try {
            lastPlayedSequenceIdDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _lastPlayedSequenceIdProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _lastPlayedSequenceIdProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.LastPlayedSequenceId: {
                    changed = _lastPlayedSequenceIdProperty.Read(stream, context);
                    if (changed) FireLastPlayedSequenceIdDidChange(lastPlayedSequenceId);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _lastPlayedSequenceId = lastPlayedSequenceId;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
